name: Android Release APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_message: ${{ steps.msg.outputs.text }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Prepare Build
        id: msg
        run: |
          chmod +x gradlew
          printf "%s" "${{ secrets.SIGNING_KEY }}" | base64 --decode > app/release-key.jks
          echo "text<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=%B >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          V_NAME=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          V_CODE=$(git tag | wc -l)
          ./gradlew assembleRelease -PAPP_VERSION_CODE=$V_CODE -PAPP_VERSION_NAME=$V_NAME
        env:
          RELEASE_STORE_FILE: release-key.jks
          RELEASE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          TAG_NAME=${{ github.ref_name }}
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/${REPO_NAME}-${TAG_NAME}.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
          body: ${{ steps.msg.outputs.text }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mirror:
    needs: build
    uses: ./.github/workflows/mirror_official.yml
    with:
      tag_name: ${{ github.ref_name }}
      release_name: ${{ github.ref_name }}
      release_body: ${{ needs.build.outputs.commit_message }}
    secrets: inherit
